# [SUIT, TYPE_ID, COST]
building_cards = [{"suit":"trade", "type_ID":0, "cost": 1},
                  {"suit":"trade", "type_ID":0, "cost": 1},
                  {"suit":"trade", "type_ID":0, "cost": 1},
                  {"suit":"trade", "type_ID":0, "cost": 1},
                  {"suit":"trade", "type_ID":0, "cost": 1},
                  {"suit":"trade", "type_ID":1, "cost": 2},
                  {"suit":"trade", "type_ID":1, "cost": 2},
                  {"suit":"trade", "type_ID":1, "cost": 2},
                  {"suit":"trade", "type_ID":2, "cost": 4},
                  {"suit":"trade", "type_ID":2, "cost": 4},
                  {"suit":"trade", "type_ID":2, "cost": 4},
                  {"suit":"trade", "type_ID":3, "cost": 2},
                  {"suit":"trade", "type_ID":3, "cost": 2},
                  {"suit":"trade", "type_ID":3, "cost": 2},
                  {"suit":"trade", "type_ID":3, "cost": 2},
                  {"suit":"trade", "type_ID":4, "cost": 5},
                  {"suit":"trade", "type_ID":4, "cost": 5},
                  {"suit":"trade", "type_ID":5, "cost": 3},
                  {"suit":"trade", "type_ID":5, "cost": 3},
                  {"suit":"trade", "type_ID":5, "cost": 3},
                  {"suit":"war", "type_ID":6, "cost": 2},
                  {"suit":"war", "type_ID":6, "cost": 2},
                  {"suit":"war", "type_ID":6, "cost": 2},
                  {"suit":"war", "type_ID":7, "cost": 3},
                  {"suit":"war", "type_ID":7, "cost": 3},
                  {"suit":"war", "type_ID":7, "cost": 3},
                  {"suit":"war", "type_ID":8, "cost": 5},
                  {"suit":"war", "type_ID":8, "cost": 5},
                  {"suit":"war", "type_ID":9, "cost": 1},
                  {"suit":"war", "type_ID":9, "cost": 1},
                  {"suit":"war", "type_ID":9, "cost": 1},
                  {"suit":"religion", "type_ID":10, "cost": 2},
                  {"suit":"religion", "type_ID":10, "cost": 2},
                  {"suit":"religion", "type_ID":10, "cost": 2},
                  {"suit":"religion", "type_ID":11, "cost": 3},
                  {"suit":"religion", "type_ID":11, "cost": 3},
                  {"suit":"religion", "type_ID":11, "cost": 3},
                  {"suit":"religion", "type_ID":12, "cost": 1},
                  {"suit":"religion", "type_ID":12, "cost": 1},
                  {"suit":"religion", "type_ID":12, "cost": 1},
                  {"suit":"lord", "type_ID":13, "cost": 4},
                  {"suit":"lord", "type_ID":13, "cost": 4},
                  {"suit":"lord", "type_ID":13, "cost": 4},
                  {"suit":"lord", "type_ID":13, "cost": 4},
                  {"suit":"lord", "type_ID":14, "cost": 3},
                  {"suit":"lord", "type_ID":14, "cost": 3},
                  {"suit":"lord", "type_ID":14, "cost": 3},
                  {"suit":"lord", "type_ID":14, "cost": 3},
                  {"suit":"lord", "type_ID":14, "cost": 3},
                  {"suit":"lord", "type_ID":15, "cost": 5},
                  {"suit":"lord", "type_ID":15, "cost": 5},
                  {"suit":"lord", "type_ID":15, "cost": 5},]

# [SUIT, TYPE_ID, COST]
unique_building_cards = [{"suit":"unique", "type_ID":16, "cost": 5},
                  {"suit":"unique", "type_ID":17, "cost": 3},
                  {"suit":"unique", "type_ID":17, "cost": 3},
                  {"suit":"unique", "type_ID":18, "cost": 6},
                  {"suit":"unique", "type_ID":19, "cost": 2},
                  {"suit":"unique", "type_ID":20, "cost": 6},
                  {"suit":"unique", "type_ID":21, "cost": 5},
                  {"suit":"unique", "type_ID":22, "cost": 5},
                  {"suit":"unique", "type_ID":23, "cost": 6},
                  {"suit":"unique", "type_ID":24, "cost": 5},
                  {"suit":"unique", "type_ID":25, "cost": 6},
                  {"suit":"unique", "type_ID":26, "cost": 6},
                  {"suit":"unique", "type_ID":27, "cost": 3},
                  {"suit":"unique", "type_ID":28, "cost": 6},
                  {"suit":"unique", "type_ID":29, "cost": 3},
                  {"suit":"unique", "type_ID":30, "cost": 5},
                  {"suit":"unique", "type_ID":31, "cost": 5},
                  {"suit":"unique", "type_ID":32, "cost": 6},
                  {"suit":"unique", "type_ID":33, "cost": 5},
                  {"suit":"unique", "type_ID":34, "cost": 4},
                  {"suit":"unique", "type_ID":35, "cost": 6},
                  {"suit":"unique", "type_ID":36, "cost": 5},
                  {"suit":"unique", "type_ID":37, "cost": 4},
                  {"suit":"unique", "type_ID":38, "cost": 6},
                  {"suit":"unique", "type_ID":39, "cost": 5},]


roles = {0: ["Assassin", "Witch", "Magistrate"],
         1: ["Thief", "Spy", "Blackmailer"],
         2: ["Magician", "Wizard", "Seer"],
         3: ["King", "Emperor", "Patrician"],
         4: ["Bishop", "Abbot", "Cardinal"],
         5: ["Merchant", "Alchemist", "Trader"],
         6: ["Architect", "Navigator", "Scholar"],
         7: ["Warlord", "Diplomat", "Marshal"],
         8: ["Queen", "Artist", "Tax Collector"]}

role_to_role_id = {'Assassin': 0,
                   'Witch': 0,
                   'Magistrate': 0,
                   'Thief': 1,
                   'Spy': 1,
                   'Blackmailer': 1,
                   'Magician': 2,
                   'Wizard': 2,
                   'Seer': 2,
                   'King': 3,
                   'Emperor': 3,
                   'Patrician': 3,
                   'Bishop': 4,
                   'Abbot': 4, 
                   'Cardinal': 4,
                   'Merchant': 5,
                   'Alchemist': 5,
                   'Trader': 5, 
                   'Architect': 6,
                   'Navigator': 6,
                   'Scholar': 6,
                   'Warlord': 7, 
                   'Diplomat': 7,
                   'Marshal': 7,
                   'Queen': 8,
                   'Artist': 8,
                   'Tax Collector': 8}
